---

- name: Installing configuration file of virtual network interface(s)
  template:
    src: virt-iface.conf.j2
    dest: /etc/sysconfig/virt-iface-{{ item.ifname }}.conf
    owner: root
    group: root
    mode: "0644"
  with_items: virtual_intefaces


- name: Installing systemd units for each of interfaces
  template:
    src: virt-iface.service.j2   
    dest: /etc/systemd/system/virt-iface-{{ item.ifname }}.service
    owner: root
    group: root
    mode: "0644"
  with_items: virtual_interfaces


- name: Reloading systemd daemon to ensure the new services are recognized properly
  command: /usr/bin/systemctl daemon-reload


- name: Ensure the new services are started and autostarted
  service: name=virt-iface-{{ item.ifname }} state=started enabled=on
  with_items: virtual_interfaces


- name: Installing ifcfg configuration
  template: 
    src: ifcfg-virt-network.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.ifname }}
    owner: root
    group: root
    mode: "0644"
  with_items: virtual_interfaces


